import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./pages/navbar";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey="pk_test_aGVscGluZy1tb25rZmlzaC02Ny5jbGVyay5hY2NvdW50cy5kZXYk"
      appearance={{
        layout: {
          socialButtonsPlacement: "bottom",
        },
      }}
    >
      <html lang="en">
        <body className={quicksand.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
